[tool.poetry]
name = "renovate-pr-truncate"
version = "0.0.0"
description = "Example of renovate truncating a PR text"
package-mode = true

[tool.poetry.dependencies]
python = "~3.10"
inboard = "^0.2.0"
faststream = "^0.1.0"
python-multipart = "^0.0.20"
odfdo = "^3.9.3"
python-json-logger = "^3.2.1"
pytest-asyncio = "^0.26.0"
aiohttp = "^3.10.10"
aioresponses = "^0.7.4"
pydantic = "^2.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
